### PR TITLE
feat: Don't display `OpenAI` models when no key

### LINKED ISSUE #1: Add support for the ability to disable certain model vendors
As much as I appreciate being able to switch model, I'd like to disable certain ones, like `openai`, so that I don't have to go back to them over an over.

Maybe a config option like `vendors` would be a good idea to allow users to customize their experience (default being both ollama and openai)

### PR DESCRIPTION
**Pull request by pillzu**
Summary:
- Add a utility function to check environment variable for OpenAI key
- Add tests for the utility function
- Add a check to code/chat windows to hide the display
- TODO: Fix tests in chat_spec/code_spec lua files

Resolves #1

### CODE REVIEW

**Comment by aaronik** [comment]
This is awesome, thank you!!

I've been crazy busy this week. I think I should be able to get to this this weekend.

**Comment by aaronik** [comment]
Hey, so sorry it's taken me so long on this - I'd been in the desert working on this, and cranked it out, then traveled up north and reintegrated with my people, and now have no time after work. I have no time for work, even -- things are crazy packed. 

I have managed to take a peek at this, but not pull it down and play with it. It looks mostly great.

I want to touch base with you about moving forward with it - since I'm so busy, I'm not sure I really can pair up or give direction. Maybe instead we can kind of popcorn it. Would you be ok if I made some commits on top of this, then handed it back to you for further work? Or would you rather I finish it at some point? Every now and then I find an hour or so, I will focus on this during those times.

**Comment by pillzu** [comment]
@Aaronik no stress man! Feel free to push commits on top of it if that's more convenient. I'll follow the PR for further updates all the time. Its also a good learning experience to see how you might refactor some of the code (it'll help me get an idea as well, so future issues can be resolved all on my own in case I'm still around)

And take your time, no hurries. Hope you've been keeping up with your health in all the hustle and bustle as well ✨ sounds pretty exhausting for sure haha

**Comment by aaronik** [comment]
Hey! I have an idea, can you make the target branch of this PR `selective-models`? Then I'll merge it right away and it'll be easier to iterate over.

**Comment by pillzu** [comment]
Done @Aaronik :)

**Comment by aaronik** [comment]
@pillzu you responded so fast even though it took me so long. Cheers to you!

**Pull request merged**
